/**
 * db.ts
 * Neon PostgreSQL connection and commitments table utilities for KOMMIT.
 *
 * Provides schema initialization, commitment persistence, and retrieval
 * using the Neon serverless driver.
 */

import { neon } from "@neondatabase/serverless";

const sql = neon(process.env.DATABASE_URL!);

/** Represents the possible lifecycle states of a commitment. */
export type CommitmentStatus = "pending" | "completed" | "forfeited";

/** Represents a single row in the commitments table. */
export interface CommitmentRow {
  id: string;
  commitment_text: string;
  stake_amount: number;
  forfeit_destination: string;
  avoided_truth: string;
  due_date: string;
  status: CommitmentStatus;
  stripe_payment_intent_id: string;
  created_at: string;
}

/**
 * initSchema
 *
 * Creates the `commitments` table if it does not already exist.
 * Safe to call on every application startup.
 *
 * @returns A promise that resolves when the schema is ready.
 */
export async function initSchema(): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS commitments (
      id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
      commitment_text         TEXT        NOT NULL,
      stake_amount            INTEGER     NOT NULL,
      forfeit_destination     TEXT        NOT NULL,
      avoided_truth           TEXT        NOT NULL,
      due_date                TIMESTAMPTZ NOT NULL,
      status                  TEXT        NOT NULL DEFAULT 'pending',
      stripe_payment_intent_id TEXT       NOT NULL,
      created_at              TIMESTAMPTZ DEFAULT NOW()
    )
  `;
}

/**
 * saveCommitment
 *
 * Inserts a new commitment row into the database and returns the
 * generated UUID as a string.
 *
 * @param data - All commitment fields except `id` and `created_at`,
 *               which are generated by the database.
 * @returns The generated `id` of the newly inserted row.
 */
export async function saveCommitment(
  data: Omit<CommitmentRow, "id" | "created_at">
): Promise<string> {
  const rows = await sql`
    INSERT INTO commitments (
      commitment_text,
      stake_amount,
      forfeit_destination,
      avoided_truth,
      due_date,
      status,
      stripe_payment_intent_id
    ) VALUES (
      ${data.commitment_text},
      ${data.stake_amount},
      ${data.forfeit_destination},
      ${data.avoided_truth},
      ${data.due_date},
      ${data.status},
      ${data.stripe_payment_intent_id}
    )
    RETURNING id
  `;

  return rows[0].id as string;
}

/**
 * getCommitment
 *
 * Retrieves a single commitment row by its UUID.
 *
 * @param id - The UUID of the commitment to retrieve.
 * @returns The matching {@link CommitmentRow}, or `null` if not found.
 */
export async function getCommitment(id: string): Promise<CommitmentRow | null> {
  const rows = await sql`
    SELECT
      id::text,
      commitment_text,
      stake_amount,
      forfeit_destination,
      avoided_truth,
      due_date::text,
      status,
      stripe_payment_intent_id,
      created_at::text
    FROM commitments
    WHERE id = ${id}::uuid
    LIMIT 1
  `;

  if (rows.length === 0) {
    return null;
  }

  const row = rows[0];

  return {
    id: row.id as string,
    commitment_text: row.commitment_text as string,
    stake_amount: row.stake_amount as number,
    forfeit_destination: row.forfeit_destination as string,
    avoided_truth: row.avoided_truth as string,
    due_date: row.due_date as string,
    status: row.status as CommitmentStatus,
    stripe_payment_intent_id: row.stripe_payment_intent_id as string,
    created_at: row.created_at as string,
  };
}